name: blog
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: 8.1.2
  collection: 1.18.0
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.9
  freezed_annotation: 2.4.1
  intl: 0.18.1
  provider: 6.1.1
  shared_preferences: 2.2.2
  url_launcher: 6.2.3

dev_dependencies:
  bloc_test: 9.1.5
  build_runner: 2.4.7
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.6
  mocktail: 1.0.2
  spider: 4.2.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/articles/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SchibstedGrotesk
      fonts:
        - asset: assets/fonts/SchibstedGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SchibstedGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SchibstedGrotesk-Bold.ttf
          weight: 700
