name: blog
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  freezed_annotation: 2.4.1
  flutter_bloc: 8.1.3
  provider: 6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.7
  bloc_test: 9.1.5
  spider: 4.2.2
  freezed: 2.4.6
  mocktail: 1.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/articles/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SchibstedGrotesk
      fonts:
        - asset: assets/fonts/SchibstedGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SchibstedGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SchibstedGrotesk-Bold.ttf
          weight: 700
